# Generated by Django 3.2.5 on 2021-07-14 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('sso_server', '0002_consumer_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
