# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import simple_sso.sso_server.models


class Migration(migrations.Migration):

    dependencies = [
        ('sso_server', '0002_consumer_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='private_key',
            field=models.CharField(default=simple_sso.sso_server.models.ConsumerSecretKeyGenerator('private_key'), max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='public_key',
            field=models.CharField(default=simple_sso.sso_server.models.ConsumerSecretKeyGenerator('public_key'), max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='access_token',
            field=models.CharField(default=simple_sso.sso_server.models.TokenSecretKeyGenerator('access_token'), max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='request_token',
            field=models.CharField(default=simple_sso.sso_server.models.TokenSecretKeyGenerator('request_token'), max_length=64, unique=True),
        ),
    ]
