[tox]
envlist =
    flake8
    isort
    black
    {py310,py311,py312}-dj42-test
    {py310,py311,py312,py313}-dj52-test
    {py312,py313}-dj60-test

[testenv]
basepython =
    py310: python3.10
    py311: python3.11
    py312: python3.12
    py313: python3.13
deps =
    -r{toxinidir}/tests/requirements.txt
    dj42: Django>=4.2,<5.0
    dj50: Django>=5.2,<6.0
    dj60: Django>=6.0,<6.1
commands =
    test: coverage erase
    test: coverage run ./runtests.py
    test: coverage report

[testenv:flake8]
deps = flake8
commands = flake8
basepython = python3.12

[testenv:isort]
deps = isort
commands = isort --check-only --diff simple_sso tests runtests.py
basepython = python3.12

[testenv:black]
basepython = python3.12
deps = black
commands = black --check --diff .
